services:
  - type: web
    name: shree-annapure-instagram-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: META_VERIFY_TOKEN
        sync: false
      - key: META_PAGE_ACCESS_TOKEN
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: INSTAGRAM_BUSINESS_ACCOUNT_ID
        sync: false
